sudo: false
language: scala
install:
  - pip install --user codecov
scala:
- "2.11.7"
script:
  - sbt clean coverage coreJVM/test
after_success:
  - codecov
  # - bash <(curl -s https://codecov.io/bash)
  - sbt coveralls
branches:
  only:
    - master
cache:
  directories:
    $HOME/.ivy2/cache
